
version: "3.8"
services:
  proxy:
    build: requirements/nginx
    container_name: proxy
    image: proxy:mine
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb:mine
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MARIADB_USER}", "-p${MARIADB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart:
      on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:mine
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      on-failure
  
  redis:
    build: requirements/bonus/redis
    container_name: redis
    image: redis:mine
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception
    restart:
      on-failure

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    image: ftp:mine
    networks:
      - inception
    restart:
      unless-stopped
    volumes:
      - wordpress:/var/www/html
      - /ftp:/home/ftpuser/ftp
    ports:
      - "21:21"
      - "20:20"
      - "21000:21000"
  
  website:
    build: requirements/bonus/website
    container_name: website
    image: website:static
    networks:
      - inception
    ports:
      - "3333:3333"
    restart:
      always
  
  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    image: adminer:om
    networks:
      - inception
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    env_file:
      - .env
    restart: always
  
  prometheus:
    build: requirements/bonus/prometheus
    container_name: prometheus
    image: prometheus:mine
    volumes:
      - prometheus:/prometheus
      - ./requirements/bonus/prometheus/tools/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - inception
    restart: always
    
  mysqld-exporter:
    build: requirements/bonus/prometheus/mariadb_exporter
    env_file:
      - .env
    ports:
      - "9104:9104"
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  nginx-exporter:
    build: requirements/bonus/prometheus/nginx_exporter
    ports:
      - "9113:9113"
    networks:
      - inception
    depends_on:
      - proxy
    restart: always
  
  redis-exporter:
    build: requirements/bonus/prometheus/redis_exporter
    ports:
      - "9121:9121"
    networks:
      - inception
    restart: always

  cadvisor:
    build: requirements/bonus/prometheus/cadvisor
    container_name: cadvisor
    image: cadvisor:mine
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro 

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/${LOGIN}/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/${LOGIN}/data/mariadb"
  prometheus:
    name: prometheus
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/${LOGIN}/data/prometheus"

networks:
  inception:
    name: inception
    driver: bridge
