
version: "3.8"
services:
  proxy:
    build: requirements/nginx
    container_name: proxy
    image: proxy:mine
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb:mine
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart:
      on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:mine
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      on-failure
  
  redis:
    build: requirements/bonus/redis
    container_name: redis
    image: redis:mine
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception
    restart:
      on-failure

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    image: ftp:mine
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inecption
    restart:
      on-failure
    volumes:
      - ftp:/etc/ftpd

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/${LOGIN}/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/${LOGIN}/data/mariadb"

networks:
  inception:
    name: inception
    driver: bridge
